### ISSUE TITLE
Integrate Google Firebase Crashlytics into iOS App

### ISSUE THREAD

**Issue by matax87** [noi-techpark/it.bz.noi.community.ios#146]
As app maintainers we want to integrate Google Firebase Crashlytics into the iOS app so that we can receive and analyze app crash reports to enhance the app’s stability and improve the user experience.

**Comment by matax87** [comment]
Testing:

We verified that Crashlytics is correctly receiving crashes from development version of the app ([see the screenshot](https://github.com/user-attachments/assets/5ca80873-a193-4fad-a4f2-983f67ae8e33))
Not verified that Crashlytics is correctly receiving crashes from release versions of the app
Not verified that dSYMs are being uploaded successfully as part of the CD pipeline.

**Comment by matax87** [comment]
In order to test points 2 and 3, we require a custom beta build of the app with the developer menu enabled (see https://github.com/noi-techpark/it.bz.noi.community.ios/pull/147#issue-2462751101).
To create this build, the following patch must be applied temporally to the CD workflow:

```diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
index 446f31f..1b308b6 100644
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -106,7 +106,7 @@ jobs:
         run: |
           set -eo pipefail
           xcodebuild clean archive \
-            -configuration "Release" \
+            -configuration "Release DEVELOPER_MENU" \
             -scheme NOICommunity \
             -sdk iphoneos \
             -archivePath "$PWD/build/NOICommunity.xcarchive" \
```

**Comment by RudiThoeni** [comment]
done
NOI Community App 1.1.4 (20241003154853) is ready to test on iOS.

**Comment by matax87** [comment]
@RudiThoeni the crash has been captured successfully by firebase Crashlytics (see https://console.firebase.google.com/project/noi-community/crashlytics/app/ios:it.bz.noi.community/issues/a421b04c5fc76eec216cc89ab0a1ba9b?time=last-seven-days&types=crash&sessionEventKey=226d4950894c404491c3bbde4fd67b32_2000047713114823222). You can roll back the CD workflow and close this user story.

Thank you
