### ISSUE TITLE
Some content is served via a insecure http connection

### ISSUE THREAD

**Issue by matax87** [noi-techpark/it.bz.noi.community.ios#23]
> Since iOS 9, Apple introduced "App Transport Security," or ATS. This defaults apps to requiring an HTTPS connection, and returning an error for non-HTTPS.

I see that a lot of events' images and other web contents are still not secure and use HTTP. This lead to errors or missing contents inside the iOS app.

I think that the same problems afflict the android apps as well.

**Comment by Piiit** [comment]
@RudiThoeni What was your endpoint again to force https images etc.... couldn't we use that in the meantime?

**Comment by RudiThoeni** [comment]
https://github.com/noi-techpark/odh-docs/wiki/How-to-get-a-Image-from-a-http-url-as-https-content

**Comment by Piiit** [comment]
@matax87 Would that solution work for you?

**Comment by matax87** [comment]
> @matax87 Would that solution work for you?

Yes, I think it would. Thank you!

**Comment by matax87** [comment]
@RudiThoeni and @Piiit I'm testing the https://images.opendatahub.bz.it/api/Image/GetImageByUrl api and I can confirm that the connection is secure and it doesn't violate Apple App Transport Security; but I get a lot of 404 not found for event at the start of 2021 (e.g. https://images.opendatahub.bz.it/api/Image/GetImageByUrl?imageurl=http://tourism.opendatahub.bz.it/imageresizer/ImageHandler.ashx?src%3Dimages/eventshort/eventshort/5219b000-5cfe-4bcf-90a8-bcb770c0c514.jpg). Is it right and the expected outcome of this api?

Thank you!

**Comment by RudiThoeni** [comment]
Hi @matax87 
We changed Imageresizer URL by April/May of 2021
Should the app also show events from the past? If yes i will fix it on api side....?

**Comment by matax87** [comment]
> Hi @matax87
> We changed Imageresizer URL by April/May of 2021
> Should the app also show events from the past? If yes i will fix it on api side....?

No. I was just testing it on old data because on the newer one I couldn't find any image url which requires http.

**Comment by RudiThoeni** [comment]
i think on the events all images of the future and up from 05/06 2021 are and will be https ;)
