### ISSUE TITLE
cd: problems while publishing as test flight

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.ios#37]
Since the last two PRs I get the following error:

```
*** SESSION AUTH: Jenga directives: {
    jenga = 1;
}
*** Error: Error uploading 'build/NOICommunity.ipa'.
*** Error: Unable to upload archive. The file 'build/NOICommunity.ipa' cannot be found. (-43)
Error: Process completed with exit code 1.
```

Any idea how to solve this?

**Comment by matax87** [comment]
@Piiit maybe the problem is that the app has been renamed to `NOI-Community`. Can you try to change from `NOICommunity.ipa` to `NOI-Community.ipa` and put an `ls build/` just to confirm my hypothesis?

Thank you!

**Comment by matax87** [comment]
@Piiit 

> @Piiit maybe the problem is that the app has been renamed to `NOI-Community`. Can you put an `ls build/` log inside workflows scripts?
> 
> Thank you!

@Piiit do you have any logs to share? Thank you!

**Comment by Piiit** [comment]
Tested it, but it still fails ... see https://github.com/noi-techpark/it.bz.noi.community.ios/runs/3792433662?check_suite_focus=true#step:10:17 It seems there is no just a placeholder name, instead of the proper one... could you please fix that, or should I just use the shown name?

**Comment by matax87** [comment]
@Piiit Ok I found the problem. Can you remove you tmp commits? Thank you

**Comment by matax87** [comment]
@Piiit solved in #40

**Comment by matax87** [comment]
@Piiit you need to revert your changes to CI workflows and use `NOICommunity.ipa` as before

**Comment by Piiit** [comment]
Thanks for your help... it is solved now
