### ISSUE TITLE
When wanting to return to the "Today"-section by swiping from left to right, no event is shown

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.ios#53]
- [ ] If I open a detail page and swipe from left to right for back-navigation (instead of tapping on the arrow in the top-navigation bar) I return to the “Today”-Section, but no Event is shown: [prntscr.com/1vtfr9a](url)

- [x] Furthermore, the date in the circle is not centered yet (probably depends on font size and type): [prntscr.com/1vtxe21](url)
     > Moved into #67

German version
Device used: iPhone11 | iOS 15.0.1 | App Version: 1.0 (202110071816000)

**Comment by Piiit** [comment]
@pkritzinger Can we close this issue, that is the first point in the main comment?

**Comment by pkritzinger** [comment]
@Piiit  - signed the issue as done - you can close, yes! thanks.
