### ISSUE TITLE
Section "Meet" - the list view should reflect the design

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.ios#55]
**Meet**
It would be great if the list view would reflect the design: Screenshot design: [prntscr.com/1vtg2zd](url) vs. App: [prntscr.com/1vtg54e](url)

German version
Device used: iPhone11 | iOS 15.0.1 | App Version: 1.0 (202110071816000)

**Comment by macteo** [comment]
I cannot open the URLs, could you please just attach the images here in the issue?
