### ISSUE TITLE
Section "Eat" - is it possible to reduce the margins between the images?

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.ios#56]
**Eat**
Is it possible to reduce the margins between the images? Screenshot: [prntscr.com/1vtxyiv](url)

German version
Device used: iPhone11 | iOS 15.0.1 | App Version: 1.0 (202110071816000)

**Comment by matax87** [comment]
> @MarE1991 We need someone with an apple device to check these issues and finally close them... who could be in charge for that?

@Piiit please remember that you'll get it on TestFlight's betas only after the MR has been merged!

**Comment by Piiit** [comment]
@MarE1991 Maybe @pkritzinger could be the right person for the iOS app to close issues?
