### ISSUE TITLE
Eat entries order and naming

### ISSUE THREAD

**Issue by matax87** [noi-techpark/it.bz.noi.community.ios#58]
> Moreover, could you please change the order of the three restaurants? The first one should be NOI-COMMUNITY BAR (written with a hyphen between), then NOISTERIA and then ALUMIX

See https://github.com/noi-techpark/it.bz.noi.community.android/issues/52

PS @Piiit we have not the power to add this issue to the Kanban board.

**Comment by Piiit** [comment]
@matax87 Let me check your permissions for the Kanban... I keep it here, please try again. You have "write" access, strange that you cannot add projects here

**Comment by Piiit** [comment]
Strange, there is no higher role... I will investigate

**Comment by matax87** [comment]
> @matax87 could you please try to access first your Kanban and then manually add this issue as card there... thanks

ok this works. Thank you 🙏 !

**Comment by pkritzinger** [comment]
@matax87 @Piiit : find a screenshot attached. Order is perfect, capital letters are missing
![Screenshot_1](https://user-images.githubusercontent.com/92454516/137716491-775b43b8-8001-4ba7-a0d8-1494fb7e5bfd.png)

![Screenshot_2](https://user-images.githubusercontent.com/92454516/137716501-c4008223-3f0b-4355-a750-06af384511ca.png)

**Comment by matax87** [comment]
> @matax87 thanks for the access. Looking at the Doc, everything should be perfectly fine as it is. Just referred my feedback to the first comment:
> 
> > The first one should be NOI-COMMUNITY BAR (written with a hyphen between), then NOISTERIA and then ALUMIX

@pkritzinger the capitalisation is just a style/design choice that applies to all entries of the eat screen or these three restaurants have names with capitalised letters? In the first case we may implement it by specifying a capitalisation style on the name/title label for each entries without any changes to localised strings.

**Comment by matax87** [comment]
Done see PR #69 and its attached screenshots
