### ISSUE TITLE
NOI Maps

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.ios#8]
Related to https://github.com/noi-techpark/it.bz.noi.community/issues/7 (not blocking)

As an app user I want to find information about where are located all services (es. restaurants, meeting rooms, etc.), companies, laboratories and institution in the park in order to find them easily.​
The data are made available through the Open Data Hub API:

Useful link for the development:
- web application: https://maps.noi.bz.it/
- web component: https://webcomponents.opendatahub.bz.it/webcomponent/9232cce6-2f39-11eb-adc1-0242ac120002
- swagger: https://swagger.opendatahub.bz.it/?url=https://mobility.api.opendatahub.bz.it/v2/apispec
- API call example: https://mobility.api.opendatahub.bz.it/v2/flat/NOI-Place?limit=-1&offset=0&select=sname,smetadata&where=smetadata.building_code.neq.null,smetadata.building_name.neq.null,sorigin.eq.office365

**Comment by Piiit** [comment]
@matax87 Please change the map URLS to this --> https://maps.noi.bz.it/en/?fullview=1&hidezoom=1 (depending on each language)... that should remove the cookie banner, zoom icons and title... thank you

**Comment by Piiit** [comment]
@matax87 If it has already been implemented... please test again, eventually you need to clear your application cache... I needed that on my Android... the new web page has been deployed 20 minutes ago... thx

**Comment by Piiit** [comment]
@pkritzinger Please test and eventually close this issue

**Comment by matax87** [comment]
> @matax87 If it has already been implemented... please test again, eventually you need to clear your application cache... I needed that on my Android... the new web page has been deployed 20 minutes ago... thx

Yes, it has been done in #48.
By the way #91 Updates the Italian orientate url

**Comment by matax87** [comment]
With the latest version it seems to work ![IMG_AB8A67C03EC8-1](https://user-images.githubusercontent.com/4108197/143411558-4e36e085-9f1b-46ac-90f2-be67a462f325.jpeg)

**Comment by pkritzinger** [comment]
<img width="414" alt="20211201_182609921_iOS" src="https://user-images.githubusercontent.com/92454516/144292073-640597cc-9780-4102-95aa-aeb043b9e3e4.png">
