### ISSUE TITLE
"Today" --> Tab nav disappears

### ISSUE THREAD

**Issue by pkritzinger** [noi-techpark/it.bz.noi.community.ios#80]
@matax87 
When selecting a filter option in the tab-nav that leads to no result (i.e. no event for that date), the tab-nav disappears. Thus, the user does not have any possibility to readjust the settings. Could we please constantly show the tab-nav - independent of the results?

![image](https://user-images.githubusercontent.com/92454516/139838588-5594207e-0aaa-48ec-8e5d-17cc6cfd413a.png)

![image](https://user-images.githubusercontent.com/92454516/139838665-11007b8e-fa5b-4fe8-834d-f07093234d21.png)

**Comment by Piiit** [comment]
@pkritzinger The new version should be out in some minutes, please test and close or comment here

**Comment by pkritzinger** [comment]
@Piiit : unfortunately I cannot check it since events are provided for each tab section. 
Another thing i found: currently no event has a description. Is this a bug or just coincidence?

**Comment by Piiit** [comment]
@pkritzinger OK I close it then... feel free to re-open if the problem returns, or is not solved
