### ISSUE TITLE
Better title in application menus

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community.ios#84]
Sometimes the title in the application menu is truncated or on two lines, better would be to have just the logo and the word "Community"... is that possible just for the menu, but still have "NOI Community" for the app name in general

**Comment by Piiit** [comment]
Discussions on https://github.com/noi-techpark/it.bz.noi.community.android/issues/73

**Comment by Piiit** [comment]
@pkritzinger Please test and eventually close this issue

**Comment by Piiit** [comment]
@pkritzinger @matax87 I have got an iPhone finally, but I am not able to install the Testflight app... it needs at least iOS 13... that is a pity... the phone is a bit older... do you know how to install and test this app on ios 12.5?

**Comment by pkritzinger** [comment]
@Piiit sorry, but I've no idea how to solve this isse :(.

**Comment by matax87** [comment]
> @pkritzinger @matax87 I have got an iPhone finally, but I am not able to install the Testflight app... it needs at least iOS 13... that is a pity... the phone is a bit older... do you know how to install and test this app on ios 12.5?

The app support just the last two available iOS versions: iOS 14 and 15; thus, you need a device with at least iOS 14.

**Comment by pkritzinger** [comment]
>Sometimes the title in the application menu is truncated or on two lines, better would be to have just the logo and the word "Community"... is that possible just for the menu, but still have "NOI Community" for the app name in general

@Piiit I don't really understand what your request is. Could you specify with screenshots pls?

**Comment by Piiit** [comment]
@pkritzinger Please see the screenshot inside https://github.com/noi-techpark/it.bz.noi.community.android/issues/73...

The final result should be that we have a NOI logo and below just the text "Community", not the 

```
NOI-Communit
y
``` 

on two lines

**Comment by pkritzinger** [comment]
![BA2FC74B-8B13-4826-BFC3-961998BAD8AA](https://user-images.githubusercontent.com/92454516/144406440-5c539f3d-281a-482b-aa24-468441a074e1.jpeg)
