### ISSUE TITLE
The "Come on Board" page isn't working

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.ios#87]
@Piiit I don't know to whom assign this, but on the Apple iPhone Pro Max of Giuseppe (you can see the app version below in the screenshot) the Come on Board page is still plain white and not working.
![image](https://user-images.githubusercontent.com/92152188/142206611-f0a4e86c-5f44-4836-a5c0-c2d023d3c05d.png)

**Comment by Piiit** [comment]
@MarE1991 This is an old version, the newest is  `1.0 (20211116080027)`... from 2021-11-16... maybe he sees some update or otherwise needs to uninstall and reinstall the app manually?

**Comment by Piiit** [comment]
@MarE1991 We released a new version yesterday, please test again and eventually close the issue...
