### ISSUE TITLE
New parameter "optimizedates" available

### ISSUE THREAD

**Issue by matax87** [noi-techpark/it.bz.noi.community.ios#92]
See https://github.com/noi-techpark/it.bz.noi.community.android/issues/79

**Comment by Piiit** [comment]
@pkritzinger Hi, please test... 

If you test it today, have a look into an event called "Kick off Meeting ZEIS...", if the date is `01.-02.12` and the time is `13:00 - 14:00` everything works correctly. Close the issue eventually

**Comment by pkritzinger** [comment]
![image](https://user-images.githubusercontent.com/92454516/144291041-a4aa359d-027a-43d1-ab47-871553bedfbe.png)
